image: python:3

before_script:
  - pip3 install bs4 urllib3
  - mkdir public

stages:
  - build

pages:
  stage: build
  script:
    - python3 filter_postes >> public/index.html
  artifacts:
    paths:
      - public
